version: '3.8'

services:
  backend:
    build:
      context: ./Backend/resume-analyzer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - frontend
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
